### ISSUE TITLE
开启后无法粘贴图片了

### ISSUE THREAD

**Issue by Ador-able** [aqpower/obsidian-Latex2MathJax#1]
东西很好用，但是就是开了以后无法粘贴图片

**Comment by aqhours** [comment]
你好，插件发布了新的版本，应该是修复了这个bug，可以下载体验一下～

**Comment by Ador-able** [comment]
nice~非常感谢

**Comment by Ador-able** [comment]
但是好像不能粘贴正常文字了

**Comment by aqhours** [comment]
QAQ很抱歉之前的软件测试没有检测出bug就发布出去了，我又发布了船新版本，应该是没有问题了！

**Comment by Ador-able** [comment]
已经很强了！节省很多时间，非常感谢

**Comment by lvguima** [comment]
> QAQ很抱歉之前的软件测试没有检测出bug就发布出去了，我又发布了船新版本，应该是没有问题了！

很好的插件，使我的ob旋转
